# Generated by Django 6.0.5 on 2026-05-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('muscle_group', models.CharField(choices=[('chest', 'Грудь'), ('back', 'Спина'), ('legs', 'Ноги'), ('shoulders', 'Плечи'), ('arms', 'Руки'), ('core', 'Кор'), ('cardio', 'Кардио')], max_length=20)),
                ('equipment', models.CharField(blank=True, max_length=100)),
                ('video_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
