# Generated by Django 6.0.5 on 2026-06-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_workoutset'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='media_file',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/'),
        ),
    ]
